// Karma configuration for EduShift Frontend.
//
// Why this file exists (Sprint 16 / INFRA-16.4):
// The CI runner (GitHub Actions) and many local dev sandboxes run headless.
// We define a `ChromeHeadlessCI` launcher with the flags that the upstream
// `karma-chrome-launcher` no longer sets by default in headless mode
// (notably `--no-sandbox`, `--disable-gpu`, and a unique user-data-dir
// per test run to avoid profile-lock issues when reusing the binary).
//
// Usage:
//   - Local interactive: `npm test` (uses default `Chrome`)
//   - Local / CI batch:  `npm run test:ci` (uses `ChromeHeadlessCI`)
//
// Configuration is generated by the Angular CLI under `angular.json` test
// target. We extend (not replace) the generated config.

module.exports = function (config) {
  config.set({
    // The Angular CLI normally injects `frameworks` automatically when
    // you don't define a karmaConfig, but as soon as we point it at a
    // custom file (via angular.json -> karmaConfig) it stops doing that.
    // Listing the framework plugins here is what makes the browser
    // produce the `__karma__.start` shim that the runner expects.
    frameworks: ['jasmine', '@angular-devkit/build-angular'],
    plugins: [
      require('karma-jasmine'),
      require('karma-chrome-launcher'),
      require('@angular-devkit/build-angular/plugins/karma'),
    ],
    customLaunchers: {
      ChromeHeadlessCI: {
        base: 'ChromeHeadless',
        flags: [
          '--no-sandbox',
          '--headless=new',
          '--disable-gpu',
          '--disable-dev-shm-usage',
          '--remote-debugging-port=9222',
          // Unique user-data-dir per test run avoids the
          // "DevToolsActivePort file doesn't exist" race when the
          // browser process is reused across runs. The path is
          // OS-aware so it works on both Windows (%TEMP%) and Linux
          // (/tmp).
          '--user-data-dir=' + (process.platform === 'win32'
            ? require('os').tmpdir() + '\\karma-chrome-' + Date.now()
            : '/tmp/karma-chrome-' + Date.now()),
        ],
      },
    },
    browsers: ['Chrome'],
    singleRun: false,
    restartOnFileChange: true,
    captureTimeout: 60000,
    browserDisconnectTimeout: 60000,
    browserNoActivityTimeout: 120000,
    // Karma 6.4 changed the default reporter to remove color codes
    // for non-TTY environments. We force them off explicitly so CI
    // logs stay clean.
    client: {
      jasmine: {
        random: false,
      },
      clearContext: false, // leave Jasmine spec runner output visible
    },
  });
};