/**
 * Centralized map of every CSS custom property the theme system writes at
 * runtime. Keep this list in sync with `src/styles/_tokens.scss`:
 *   - new variables → add a row here AND a default in `_tokens.scss`
 *   - removed       → drop from both files
 *
 * `TenantThemeService` uses this list to apply / clear tenant overrides, so
 * adding a new tenant-tweakable token is one edit per file.
 */

import type { Shade } from './color.utils';

/* Shade is owned by `color.utils.ts`. We re-list the values here as a
 * runtime-iterable array so services can `.forEach()` over them without
 * pulling in the math file. */
const SHADES = [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950] as const;
export const PALETTE_SHADES: readonly Shade[] = SHADES;

/** CSS variables for a full 11-step palette of `name` (e.g. `primary`). */
export function paletteVars(name: 'primary' | 'accent'): readonly string[] {
  return SHADES.map((s) => `--color-${name}-${s}`);
}

/**
 * Token catalog. Each entry documents what the tenant controls and where the
 * default lives. Used by `TenantThemeService` for symmetric apply/clear.
 */
export const THEME_TOKENS = {
  /** Brand colors generated by `buildPalette(primaryColor)`. */
  primaryPalette: paletteVars('primary'),

  /** Secondary brand color. Used sparingly for highlights, badges. */
  accentPalette: paletteVars('accent'),

  /** Base border-radius applied across `.btn`, `.card`, `.input`, etc. */
  radius: '--radius-base',

  /** Sans font stack. Tenant-provided value is prepended to the default. */
  fontSans: '--font-sans',
} as const;

/** Convenience: every variable name written by the tenant theme as a flat list. */
export const ALL_TENANT_VARS: readonly string[] = [
  ...THEME_TOKENS.primaryPalette,
  ...THEME_TOKENS.accentPalette,
  THEME_TOKENS.radius,
  THEME_TOKENS.fontSans,
];
